package com.example.vrsbsplayer

import android.net.Uri
import android.opengl.GLSurfaceView
import android.os.Build
import android.os.Bundle
import android.os.Handler
import android.os.Looper
import android.util.DisplayMetrics
import android.view.LayoutInflater
import android.view.View
import android.view.WindowManager
import android.widget.Button
import android.widget.FrameLayout
import android.widget.SeekBar
import android.widget.TextView
import android.widget.Toast
import androidx.activity.ComponentActivity
import androidx.core.view.WindowCompat
import androidx.core.view.WindowInsetsCompat
import androidx.core.view.WindowInsetsControllerCompat
import androidx.media3.common.MediaItem
import androidx.media3.common.PlaybackException
import androidx.media3.common.Player
import androidx.media3.common.VideoSize
import androidx.media3.exoplayer.ExoPlayer
import com.example.vrsbsplayer.profile.ProfileRepository
import com.example.vrsbsplayer.render.StereoGLRenderer
import com.example.vrsbsplayer.render.StereoMode
import java.util.Locale

@androidx.annotation.OptIn(markerClass = [androidx.media3.common.util.UnstableApi::class])
class VrPlayerActivity : ComponentActivity() {

    companion object {
        const val EXTRA_VIDEO_URI = "extra_video_uri"
        const val EXTRA_STEREO_MODE = "extra_stereo_mode" // name of StereoMode enum
        /** Optional: MIME type from the sending app's intent, e.g. "video/mp4" or
         *  "application/x-mpegURL". Passed through so ExoPlayer can pick the right
         *  media source (HLS/DASH/progressive) even when the URL has no useful
         *  extension, which is common for links generated by streaming addons. */
        const val EXTRA_MIME_TYPE = "extra_mime_type"
        /** Optional: display title from the sending app, shown briefly on entry. */
        const val EXTRA_TITLE = "extra_title"
        /** Optional: start position in milliseconds, e.g. resuming a stream. */
        const val EXTRA_START_POSITION_MS = "extra_start_position_ms"
    }

    private lateinit var glView: GLSurfaceView
    private lateinit var renderer: StereoGLRenderer
    private var player: ExoPlayer? = null
    private lateinit var repo: ProfileRepository
    private var videoUriString: String? = null
    private var videoMimeType: String? = null
    private var videoTitle: String? = null
    private var startPositionMs: Long = 0L
    private var playerAttached = false

    // --- Playback controls overlay ---
    private lateinit var controlsRoot: View
    private lateinit var playPauseButton: Button
    private lateinit var seekBar: SeekBar
    private lateinit var currentTimeText: TextView
    private lateinit var durationText: TextView
    private val uiHandler = Handler(Looper.getMainLooper())
    private var userIsScrubbing = false
    private var controlsVisible = false
    private var durationMs: Long = 0L

    /** Polls player position while the overlay is visible; ExoPlayer has no position-changed
     *  listener, so a simple periodic poll is the standard approach for a scrubber. */
    private val progressTicker = object : Runnable {
        override fun run() {
            updateProgressUi()
            uiHandler.postDelayed(this, 500L)
        }
    }

    /** Hides the overlay after a few seconds of inactivity, but only while actually
     *  playing - if the video is paused, the person likely wants the controls to stay
     *  put rather than having to tap again to bring them back. */
    private val autoHideTask = Runnable {
        if (player?.isPlaying == true) setControlsVisible(false)
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        repo = ProfileRepository(this)
        enterImmersiveMode()
        window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            // Draw into the cutout area too, so the GL surface really is the whole panel,
            // which is what the millimetre based optics below assume.
            window.attributes.layoutInDisplayCutoutMode =
                WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_ALWAYS
        }

        videoUriString = intent.getStringExtra(EXTRA_VIDEO_URI)
        videoMimeType = intent.getStringExtra(EXTRA_MIME_TYPE)
        videoTitle = intent.getStringExtra(EXTRA_TITLE)
        startPositionMs = intent.getLongExtra(EXTRA_START_POSITION_MS, 0L)
        val modeName = intent.getStringExtra(EXTRA_STEREO_MODE) ?: StereoMode.FULL_SBS.name
        val mode = try { StereoMode.valueOf(modeName) } catch (e: Exception) { StereoMode.FULL_SBS }

        val profiles = repo.loadAll()
        val selected = profiles.firstOrNull { it.id == repo.lastSelectedProfileId } ?: profiles.first()

        renderer = StereoGLRenderer(
            onSurfaceReady = { surface -> runOnUiThread { attachPlayer(surface) } },
            onFrameAvailable = { if (::glView.isInitialized) glView.requestRender() }
        )
        renderer.profile = selected
        renderer.stereoMode = mode
        renderer.setScreenPhysicalSizeMm(screenWidthMm(), screenHeightMm())

        glView = GLSurfaceView(this).apply {
            setEGLContextClientVersion(2)
            preserveEGLContextOnPause = true
            setRenderer(renderer)
            renderMode = GLSurfaceView.RENDERMODE_WHEN_DIRTY
            // Tap anywhere to reveal (or hide) the controls overlay, instead of directly
            // toggling playback - now that there's a real play/pause button, a bare tap
            // hijacking playback would fight with trying to reach the seek bar.
            setOnClickListener { setControlsVisible(!controlsVisible) }
        }

        val root = FrameLayout(this)
        root.addView(glView, FrameLayout.LayoutParams(FrameLayout.LayoutParams.MATCH_PARENT, FrameLayout.LayoutParams.MATCH_PARENT))

        controlsRoot = LayoutInflater.from(this).inflate(R.layout.vr_player_controls, root, false)
        root.addView(controlsRoot, FrameLayout.LayoutParams(FrameLayout.LayoutParams.MATCH_PARENT, FrameLayout.LayoutParams.WRAP_CONTENT))
        controlsRoot.visibility = View.GONE

        playPauseButton = controlsRoot.findViewById<Button>(R.id.playPauseButton)
        seekBar = controlsRoot.findViewById<SeekBar>(R.id.seekBar)
        currentTimeText = controlsRoot.findViewById<TextView>(R.id.currentTimeText)
        durationText = controlsRoot.findViewById<TextView>(R.id.durationText)
        val titleText = controlsRoot.findViewById<TextView>(R.id.controlsTitle)
        if (!videoTitle.isNullOrBlank()) {
            titleText.text = videoTitle
            titleText.visibility = View.VISIBLE
        }

        playPauseButton.setOnClickListener {
            togglePlayback()
            updatePlayPauseIcon()
            scheduleAutoHide()
        }
        controlsRoot.findViewById<Button>(R.id.back30).setOnClickListener { seekBy(-30_000); scheduleAutoHide() }
        controlsRoot.findViewById<Button>(R.id.back20).setOnClickListener { seekBy(-20_000); scheduleAutoHide() }
        controlsRoot.findViewById<Button>(R.id.back10).setOnClickListener { seekBy(-10_000); scheduleAutoHide() }
        controlsRoot.findViewById<Button>(R.id.forward10).setOnClickListener { seekBy(10_000); scheduleAutoHide() }
        controlsRoot.findViewById<Button>(R.id.forward20).setOnClickListener { seekBy(20_000); scheduleAutoHide() }
        controlsRoot.findViewById<Button>(R.id.forward30).setOnClickListener { seekBy(30_000); scheduleAutoHide() }
        seekBar.setOnSeekBarChangeListener(object : SeekBar.OnSeekBarChangeListener {
            override fun onProgressChanged(bar: SeekBar, progress: Int, fromUser: Boolean) {
                if (fromUser) currentTimeText.text = formatTime(progressToMs(progress))
            }
            override fun onStartTrackingTouch(bar: SeekBar) {
                userIsScrubbing = true
                uiHandler.removeCallbacks(autoHideTask)
            }
            override fun onStopTrackingTouch(bar: SeekBar) {
                userIsScrubbing = false
                player?.seekTo(progressToMs(bar.progress))
                scheduleAutoHide()
            }
        })

        setContentView(root)
    }

    private fun realMetrics(): DisplayMetrics {
        val metrics = DisplayMetrics()
        @Suppress("DEPRECATION")
        windowManager.defaultDisplay.getRealMetrics(metrics)
        return metrics
    }

    /** Long side of the panel in millimetres: the app runs locked to landscape. */
    private fun screenWidthMm(): Float {
        val m = realMetrics()
        val longPx = maxOf(m.widthPixels, m.heightPixels).toFloat()
        return if (m.xdpi > 1f) longPx / m.xdpi * 25.4f else 150f
    }

    private fun screenHeightMm(): Float {
        val m = realMetrics()
        val shortPx = minOf(m.widthPixels, m.heightPixels).toFloat()
        return if (m.ydpi > 1f) shortPx / m.ydpi * 25.4f else 70f
    }

    private fun togglePlayback() {
        val exo = player ?: return
        if (exo.isPlaying) exo.pause() else exo.play()
    }

    private fun setControlsVisible(visible: Boolean) {
        controlsVisible = visible
        controlsRoot.visibility = if (visible) View.VISIBLE else View.GONE
        uiHandler.removeCallbacks(autoHideTask)
        uiHandler.removeCallbacks(progressTicker)
        if (visible) {
            updatePlayPauseIcon()
            updateProgressUi()
            uiHandler.post(progressTicker)
            scheduleAutoHide()
        }
    }

    private fun scheduleAutoHide() {
        uiHandler.removeCallbacks(autoHideTask)
        uiHandler.postDelayed(autoHideTask, 4000L)
    }

    private fun seekBy(deltaMs: Long) {
        val exo = player ?: return
        val target = (exo.currentPosition + deltaMs).coerceIn(0L, durationMs.takeIf { it > 0 } ?: Long.MAX_VALUE)
        exo.seekTo(target)
        updateProgressUi()
    }

    private fun updatePlayPauseIcon() {
        if (!::playPauseButton.isInitialized) return
        playPauseButton.text = if (player?.isPlaying == true) "⏸" else "▶"
    }

    /** Refreshes the scrubber and time labels from the player's actual position. Skipped
     *  while the person has a finger on the seek bar, so their drag isn't fought over. */
    private fun updateProgressUi() {
        if (userIsScrubbing || !::seekBar.isInitialized) return
        val exo = player ?: return
        val posMs = exo.currentPosition.coerceAtLeast(0L)
        currentTimeText.text = formatTime(posMs)
        if (durationMs > 0L) {
            seekBar.progress = ((posMs * 1000) / durationMs).toInt().coerceIn(0, 1000)
        }
    }

    private fun progressToMs(progress: Int): Long =
        if (durationMs > 0L) (durationMs * progress) / 1000 else 0L

    private fun formatTime(ms: Long): String {
        val totalSeconds = ms / 1000
        val h = totalSeconds / 3600
        val m = (totalSeconds % 3600) / 60
        val s = totalSeconds % 60
        return if (h > 0) String.format(Locale.US, "%d:%02d:%02d", h, m, s)
        else String.format(Locale.US, "%d:%02d", m, s)
    }

    private fun attachPlayer(surface: android.view.Surface) {
        val uriString = videoUriString
        if (uriString == null) {
            Toast.makeText(this, "No video was passed to the VR view.", Toast.LENGTH_LONG).show()
            return
        }
        // onSurfaceCreated runs again after a GL context loss, so reuse the player and
        // only swap its output surface instead of building a second one.
        val existing = player
        if (existing != null) {
            existing.setVideoSurface(surface)
            return
        }

        val exo = ExoPlayer.Builder(this).build()
        exo.addListener(object : Player.Listener {
            override fun onVideoSizeChanged(videoSize: VideoSize) {
                renderer.setVideoSize(
                    videoSize.width, videoSize.height, videoSize.pixelWidthHeightRatio
                )
                glView.requestRender()
            }

            override fun onPlaybackStateChanged(playbackState: Int) {
                if (playbackState == Player.STATE_READY) {
                    durationMs = exo.duration.coerceAtLeast(0L)
                    durationText.text = formatTime(durationMs)
                    updateProgressUi()
                }
            }

            override fun onIsPlayingChanged(isPlaying: Boolean) {
                updatePlayPauseIcon()
            }

            override fun onPlayerError(error: PlaybackException) {
                Toast.makeText(
                    this@VrPlayerActivity,
                    "Playback error: ${error.errorCodeName}",
                    Toast.LENGTH_LONG
                ).show()
            }
        })
        exo.setVideoSurface(surface)
        val mediaItem = MediaItem.Builder()
            .setUri(Uri.parse(uriString))
            .apply { videoMimeType?.let { setMimeType(it) } }
            .build()
        exo.setMediaItem(mediaItem, startPositionMs)
        exo.repeatMode = Player.REPEAT_MODE_ONE
        exo.prepare()
        exo.playWhenReady = true
        player = exo
        playerAttached = true
    }

    private fun enterImmersiveMode() {
        WindowCompat.setDecorFitsSystemWindows(window, false)
        val controller = WindowCompat.getInsetsController(window, window.decorView)
        controller.hide(WindowInsetsCompat.Type.systemBars())
        controller.systemBarsBehavior = WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE
    }

    override fun onWindowFocusChanged(hasFocus: Boolean) {
        super.onWindowFocusChanged(hasFocus)
        if (hasFocus) enterImmersiveMode()
    }

    override fun onPause() {
        super.onPause()
        player?.playWhenReady = false
        if (::glView.isInitialized) glView.onPause()
    }

    override fun onResume() {
        super.onResume()
        if (::glView.isInitialized) glView.onResume()
        // Keep the optics in step with the current panel size.
        renderer.setScreenPhysicalSizeMm(screenWidthMm(), screenHeightMm())
        if (playerAttached) player?.playWhenReady = true
    }

    override fun onDestroy() {
        uiHandler.removeCallbacksAndMessages(null)
        player?.setVideoSurface(null)
        player?.release()
        player = null
        renderer.release()
        super.onDestroy()
    }
}
